version: "3"
services:
  ros2:
    container_name: ros2
    image: ros2
    build:
      context: .
      args:
        - USER_NAME=${USER_NAME}
        - GROUP_NAME=${GROUP_NAME}
        - UID=${UID}
        - GID=${GID}
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority/:/root/.Xauthority
      - ${WORKSPACE_DIR}:/home//kousei/robotics
    tty: true
    user: "${UID}:${GID}"
