FROM n622jwith/ros2_basic:latest

# install zenoh-bridge-dds
#RUN curl -sSL --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# RUN source "$HOME/.cargo/env"
# RUN apt-get install -y clang
# RUN git clone https://github.com/eclipse-zenoh/zenoh-plugin-dds.git -b 0.10.1-rc
# RUN cargo build --release -p zenoh-bridge-dds

CMD ["/bin/bash"]
