version: "3"

services:
  usb_test:
    container_name: usb_test
    build:
      context: .
      args:
        - USER_NAME=${USER_NAME}
        - GROUP_NAME=${GROUP_NAME}
        - PASSWORD=${PASSWORD}
        - UID=${UID}
        - GID=${GID}
        - GIT_USER_NAME=${GIT_USER_NAME}
        - GIT_USER_EMAIL=${GIT_USER_EMAIL}
      dockerfile: Dockerfile
    image: n622jwith/git_test:latest
    environment:
      - DISPLAY=${DISPLAY}
      - "QT_X11_NO_MITSHM=1"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority/:/root/.Xauthority:ro
      - $HOME/.ssh:$HOME/.ssh:ro
    hostname: usb_test
    tty: true
    privileged: true
    user: "${UID}:${GID}"
