version: "3"

services:
  host1:
    container_name: ros2_network
    build:
      context: .
      dockerfile: Dockerfile
    hostname: ros2_network
    networks:
      ros2-network:
        ipv4_address: 192.168.100.221
    tty: true
    user: "${UID}:${GID}"
networks:
  ros2-network:
    external: true
