version: "3"

services:
  ros2_gz:
    container_name: ros2_gz
    build:
      context: .
      args:
        - USER_NAME=${USER_NAME}
        - GROUP_NAME=${GROUP_NAME}
        - PASSWORD=${PASSWORD}
        - UID=${UID}
        - GID=${GID}
      dockerfile: Dockerfile
    image: n622jwith/ros2_gz:latest
    environment:
      - DISPLAY=${DISPLAY}
      - "QT_X11_NO_MITSHM=1"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority/:/root/.Xauthority:ro
    hostname: ros2_gz
    network_mode: "host"
    tty: true
    user: "${UID}:${GID}"
